# Generated by Django 5.0.4 on 2024-04-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nivel',
            field=models.SmallIntegerField(choices=[(1, 'NIVEL 1'), (2, 'NIVEL 2'), (3, 'NIVEL 3'), (4, 'NIVEL 4')]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('O', 'ABIERTO'), ('P', 'PENDIENTE'), ('C', 'COMPLETADO')], default='ABIERTO', max_length=1),
        ),
    ]
