# Generated by Django 5.0.4 on 2024-04-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_alter_categoria_nivel_alter_ticket_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('O', 'ABIERTO'), ('P', 'PENDIENTE'), ('C', 'COMPLETADO')], default='O', max_length=1),
        ),
    ]
