# Generated by Django 5.0.4 on 2024-04-24 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_alter_ticket_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=70)),
                ('publicacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField()),
                ('adjunto', models.FileField(upload_to='adjuntos')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket')),
            ],
        ),
    ]
