# Generated by Django 5.0.4 on 2024-04-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='adjunto',
            field=models.FileField(blank=True, upload_to='adjuntos'),
        ),
    ]
